### ISSUE TITLE
Inline not working

### ISSUE THREAD

**Issue by LeviSnoot** [hemantapkh/TokMate#2]
I've deployed the bot according to the instructions provided (minus having to edit a couple of syntax errors in one the migrations.py and tokmate.py files to get it working). Everything's working great, except for the inline function which appears to not do anything at all. When I type "@mybot" in Telegram, no menu appears, no loading circle or anything. I'm a bit stuck here.

**Comment by hemantapkh** [comment]
Make sure you have enabled Inline Mode for your bot in Bot Father.

**Comment by LeviSnoot** [comment]
You're completely right, I missed that entirely. Thanks!

**Comment by hemantapkh** [comment]
Make sure you have enabled Inline mode for your bot in Bot father.

Sent from Yahoo Mail on Android 
 
  On Tue, Aug 16, 2022 at 4:24 PM, ***@***.***> wrote:   


I've deployed the bot according to the instructions provided (minus having to edit a couple of syntax errors in one the migrations.py and tokmate.py files to get it working). Everything's working great, except for the inline function which appears to not do anything at all. When I type ***@***.***" in Telegram, no menu appears, no loading circle or anything. I'm a bit stuck here.
